### ISSUE TITLE
Use runtime config for the MONGODB_URI?

### ISSUE THREAD

**Issue by nathan1658** [arashsheyda/nuxt-mongoose#44]
It seem the URI is required during build time. Is it possible to use runtime config so when I dockerize the application i can do something like
```
docker run --env NUXT_MONGODB_URI=xxxxxxx
```

**Comment by arashsheyda** [comment]
yes you can use runtime config with the varable `MONGODB_URI`

**Comment by nathan1658** [comment]
Hi, can you elaborate more on how can I achieve this?
This is my nuxt.config:
```
export default defineNuxtConfig({
  mongoose: {
    uri: process.env.MONGODB_URI,
    options: {},
  },
})
```

And this is my dockerfile:
```
FROM node:lts as builder

WORKDIR /app

COPY . .
RUN npm i
RUN npm run build

# Nuxt 3 production
FROM node:lts

WORKDIR /app

COPY --from=builder /app/.output  /app/.output

ENV NITRO_PORT=80

EXPOSE 80

CMD [ "node", ".output/server/index.mjs" ]
```

And this is what i want to archive:
```
docker run --rm -p 8081:80 \
--env NUXT_MONGODB_URI="mongodb+srv://xxxxxxxx" \
nuxt3-test
```

However, during the docker build process, I can see the error like `Missing MongoDB URI. ` May I know how can I resolve it? Thank you so much!

**Comment by arashsheyda** [comment]
make sure to use the same variable name in your `nuxt.config` and `docker` command, they both should be `MONGODB_URI` in this case (you can change it to whatever you want, just make sure that it is the same in `nuxt.config.mongoose.uri`)

``` bash
docker run -rm -p 8081:80 -e MONGODB_URI=your-mongodb-uri nuxt3-test
```


``` ts
export default defineNuxtConfig({
  mongoose: {
    uri: process.env.MONGODB_URI, // this is the uri by default, you can remove this lines
    options: {},
  },
})
```

**Comment by nathan1658** [comment]
Hello,

It appears that the `MONGODB_URI` is determined at build time and it cannot be modified subsequently. I have tried to update my `.env` file to:

```bash
MONGODB_URI=mongodb://aaaaa
```

Afterwards, I ran:

```bash
npm run build
```

However, when I attempted to change the `MONGODB_URI` and run the server:

```bash
MONGODB_URI=mongodb://bbbb node .output/server/index.mjs  
```

The application still used `mongodb://aaaaa` as the database URI.

Furthermore, in my specific case, I observed that the `MONGODB_URI` environment variable must be present during build time. If not, I encounter the following error:

```bash
(node-resolve plugin) Could not resolve import "#nuxt/mongoose" in xxxxxx .ts using imports defined in xxxxx/package.json.
```

If I then try to run the server with a different `MONGODB_URI`:

```bash
MONGODB_URI=mongodb://bbbb node .output/server/index.mjs  
```

I receive another error:

```bash
[nuxt] [request error] [unhandled] [500] MODEL is not defined
  at ./.output/server/chunks/index.get9.mjs:13:20  
  at ./.output/server/chunks/nitro/node-server.mjs:2140:47  
  at async Object.handler (./.output/server/chunks/nitro/node-server.mjs:2202:19)  
  at async Server.toNodeHandle (./.output/server/chunks/nitro/node-server.mjs:2391:7)
```

I would appreciate any guidance or suggestions on how to address these issues. Thanks in advance for your assistance.

**Comment by Joshua-Noakes1** [comment]
@arashsheyda I'm having the same issue as Nathan when trying to build a docker container using Github Actions, I can't change the mongo uri after the build. I'm happy to provide logs from my container if it helps.

**Comment by kevinstory** [comment]
Can we please reopen this issue as it is not resolved? Runtime values will not overwrite variables set at build time.

**Comment by kevinstory** [comment]
Actually, from my testing just not, it looks like this can be overwritten with the environment variable named NUXT_MONGOOSE_URI and not MONGODB_URI.

**Comment by arashsheyda** [comment]
@kevinstory oh that's great then!! thanks a lot (sorry I don't have docker to test)

**Comment by gamegine** [comment]
works with the latest version (1.0.6)
```js
export default defineNuxtConfig({
	modules: ["nuxt-mongoose"],
	runtimeConfig: {
		mongoose: { uri: process.env.NUXT_MONGOOSE_URI },
	},
});
```
change the config env from MONGODB_URI to NUXT_MONGOOSE_URI as specified in https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables.

can also be but not tested with the options
```js
mongoose: { 
	uri: process.env.NUXT_MONGOOSE_URI },
	options: process.env.NUXT_MONGOOSE_OPTIONS },
}
```

**Comment by arshx86** [comment]
it seems nuxt-mongoose ignores environment variables.

I have;
```js
  mongoose: {
    uri: process.env.NODE_ENV === "production" ? process.env.MONGODB_PROD : process.env.MONGODB_DEV,
  },
```

and both variable defined in .env, i am getting error:
`[nuxi 23:10:04] ℹ Restarting Nuxt due to error: MongooseError: The uri parameter to openUri() must be a string, got "undefined". Make sure the first parameter to mongoose.connect() or mongoose.createConnection() is a string.`

I tried runtimeConfig too but same, I can't get environment variables working. Any help?

**Comment by gamegine** [comment]
Yes, as stated in the previous message, you must use `NUXT_MONGOOSE_URI`, which is interpreted at runtime while `MONGOOSE_URI` is defined statically at build time.

> change the config env from MONGODB_URI to NUXT_MONGOOSE_URI as specified in https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables.

**Comment by StreakingMan** [comment]
Although the reason is explained at nuxt docs, I think this issue really should be clarified in the documentation of nuxt-mongoose itself.

**Comment by arashsheyda** [comment]
the docs should be updated now, note: this is a breaking change as we renamed `MONGODB_URI` to `NUXT_MONGOOSE_URI`
