### ISSUE TITLE
Problem with cloudflare pages

### ISSUE THREAD

**Issue by DavidFrings** [arashsheyda/nuxt-mongoose#71]
logs:
```rust
Nuxt 3.14.1592 with Nitro 2.10.4                                                                              21:41:59

[21:42:02]  ERROR  (node:27436) ExperimentalWarning: CommonJS module PATH\node_modules\.pnpm\debug@4.4.0_supports-color@9.4.0\node_modules\debug\src\node.js is loading ES Module PATH\node_modules\.pnpm\supports-color@9.4.0\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use node --trace-warnings ... to show where the warning was created)

√ nuxt-mongoose is ready!                                                                                     21:42:04
i Running with compatibility version 4                                                                        21:42:04
i Building client...                                                                                          21:42:06
i vite v5.4.11 building for production...                                                                     21:42:06
i ✓ 236 modules transformed.                                                                                  21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/manifest.json                     6.40 kB │ gzip:  0.84 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/Coding.B9-Nh1_1.webp       42.29 kB                     21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/icon.Cb5jbPcQ.png       2,882.02 kB                     21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/fosAdmin.Y11VuzY0.css       0.38 kB │ gzip:  0.26 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/index.BNdK-xfe.css          0.85 kB │ gzip:  0.33 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/fosGame.-ucchkDu.css        1.64 kB │ gzip:  0.62 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/error-500.D2XqKfCx.css      1.88 kB │ gzip:  0.72 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/fos.CX8L99hq.css            2.12 kB │ gzip:  0.73 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/error-404.BIa7PHrX.css      3.56 kB │ gzip:  1.10 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/projects.7xsUzbPg.css       3.73 kB │ gzip:  1.07 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/skills.BHDvTHw0.css         4.26 kB │ gzip:  0.69 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/entry.Ca5_MifB.css          4.90 kB │ gzip:  1.54 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/CtIoigON.js                 0.16 kB │ gzip:  0.15 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/DvjBGjJe.js                 1.02 kB │ gzip:  0.61 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/BMrC8GdI.js                 1.44 kB │ gzip:  0.80 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/Ck-A5orV.js                 1.57 kB │ gzip:  0.53 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/Dkw_57lj.js                 1.63 kB │ gzip:  0.93 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/dKtWQQQo.js                 3.19 kB │ gzip:  1.44 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/BLDQIa_N.js                 3.39 kB │ gzip:  1.52 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/CwxzPXla.js                 3.73 kB │ gzip:  1.68 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/B9K5rw8f.js                 5.72 kB │ gzip:  2.35 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/DGexsP0l.js                11.02 kB │ gzip:  4.59 kB    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/BgfasTzT.js               265.61 kB │ gzip: 96.42 kB    21:42:08
i ✓ built in 2.55s                                                                                            21:42:08
√ Client built in 2569ms                                                                                      21:42:08
i Building server...                                                                                          21:42:08
i vite v5.4.11 building SSR bundle for production...                                                          21:42:08
i ✓ 1 modules transformed.                                                                                    21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/server/styles.mjs  0.07 kB                                           21:42:08
i ../node_modules/.cache/nuxt/.nuxt/dist/server/server.mjs  0.10 kB │ map: 0.09 kB                            21:42:08
i ✓ built in 17ms                                                                                             21:42:08
√ Server built in 26ms                                                                                        21:42:08
√ Generated public dist                                                                                 nitro 21:42:09

PWA v0.21.1
mode      generateSW
precache  3 entries (0.41 KiB)
files generated
  ../dist/sw.js
  ../dist/workbox-4723e66c.js
i Building Nuxt Nitro server (preset: cloudflare-pages, compatibility date: 2024-04-03)                 nitro 21:42:11

[nitro 21:42:21]  ERROR  Error: Cannot resolve "../build/Debug/kerberos.node" from "PATH\node_modules\\.pnpm\\kerberos@2.2.1\\node_modules\\kerberos\\lib\\util.js" and externals are not allowed!


undefined


[21:42:21]  ERROR  Cannot resolve "../build/Debug/kerberos.node" from "PATH\node_modules\\.pnpm\\kerberos@2.2.1\\node_modules\\kerberos\\lib\\util.js" and externals are not allowed!    

  at Object.resolveId (PATH\node_modules/.pnpm/nitropack@2.10.4_encoding@0.1.13_typescript@5.7.2/node_modules/nitropack/dist/rollup/index.mjs:1949:17)
  at async PluginDriver.hookFirstAndGetPlugin (PATH\node_modules/.pnpm/rollup@4.28.1/node_modules/rollup/dist/es/shared/node-entry.js:20712:28)
  at async resolveId (PATH\node_modules/.pnpm/rollup@4.28.1/node_modules/rollup/dist/es/shared/node-entry.js:19316:26)
  at async ModuleLoader.resolveId (PATH\2.0/node_modules/.pnpm/rollup@4.28.1/node_modules/rollup/dist/es/shared/node-entry.js:19745:15)
  at async PATH\node_modules/.pnpm/@rollup+plugin-commonjs@28.0.1_rollup@4.28.1/node_modules/@rollup/plugin-commonjs/dist/es/index.js:797:16
  at async Promise.all (index 1)
  at async PATH\node_modules/.pnpm/@rollup+plugin-commonjs@28.0.1_rollup@4.28.1/node_modules/@rollup/plugin-commonjs/dist/es/index.js:789:32
  at async rewriteRequireExpressionsAndGetImportBlock (PATH\node_modules/.pnpm/@rollup+plugin-commonjs@28.0.1_rollup@4.28.1/node_modules/@rollup/plugin-commonjs/dist/es/index.js:1367:28)    
  at async transformCommonjs (PATH\node_modules/.pnpm/@rollup+plugin-commonjs@28.0.1_rollup@4.28.1/node_modules/@rollup/plugin-commonjs/dist/es/index.js:1956:23)
  at async transform (PATH\node_modules/.pnpm/rollup@4.28.1/node_modules/rollup/dist/es/shared/node-entry.js:19663:16)
  at async ModuleLoader.addModuleSource (PATH\node_modules/.pnpm/rollup@4.28.1/node_modules/rollup/dist/es/shared/node-entry.js:19879:36)



[21:42:21]  ERROR  Cannot resolve "../build/Debug/kerberos.node" from "PATH\node_modules\\.pnpm\\kerberos@2.2.1\\node_modules\\kerberos\\lib\\util.js" and externals are not allowed!    

 ELIFECYCLE  Command failed with exit code 1.

Process finished with exit code 1
```

**Comment by jgreer9514** [comment]
I did a "npm install @aws-sdk/credential-providers" and then it got to a few other packages that were failing as well.  Eventually I'm stuck at:
[nitro 5:46:54 PM]  ERROR  Error: Cannot resolve "../build/Debug/zstd.node" from ".../node_modules/@mongodb-js/zstd/lib/index.js" and externals are not allowed!
